Fix stop button not working
sugarlabs/tictactoe pull request #6
Opened 2023-03-26 22:12 UTC by sparshg

@chimosky Sometimes the stop button doesn't work (like while I was porting the activity to flatpak, or directly running through `sugar-activity3` command. This change will fix that.

2023-06-24 12:10 UTC, sparshg commented
@chimosky Can you review this, we can bump up the version then and I will work on the flatpak then

2023-06-24 14:49 UTC, chimosky requested changes

2023-06-24 14:49 UTC, chimosky commented on activity.py
> +        Activity.close(self, **kwargs)
This isn't needed as the stop button has a cb that handles activity close.

2023-06-26 17:35 UTC, sparshg commented
@chimosky Cleaned up the commits and removed unnecessary changes

2023-06-26 22:18 UTC, merged